### ISSUE TITLE
Deployment stuck and pending forever

### ISSUE THREAD

**Issue by clemlak** [nosuchip/truffle-privatekey-provider#10]
Hello!
I tried to deploy a contract yesterday on Ropsten but the deployment seemed to be stuck. I tried to increase the gas price a couple of times and I've waited more than 600 seconds but nothing happened. When I switched to a HDWalletProvider, the deployment was immediately successful.
Any idea of what is going on?

**Comment by nosuchip** [comment]
- What version of package you using?
- Do you have minimalistic repo that demonstrate this issue?

**Comment by nosuchip** [comment]
Closed due lack of feedback. I am unable to reproduce it now.

**Comment by clemlak** [comment]
Hey @nosuchip! Sorry for the delay.
Basically the issue (and the solution) is exactly what is described here #11

So this issue can stay closed since we already have the solution :)
