### ISSUE TITLE
when using provider for test suite it must be wrapped in a function!

### ISSUE THREAD

**Issue by significance** [nosuchip/truffle-privatekey-provider#11]
when using provider for test suite it must be wrapped in a function!

```
provider: new PrivateKeyProvider(pk, "https://geth-noordung.fairdatasociety.org"),
```

hangs on prepare suite for `truffle test --network noordung`

```
provider: () => { return new PrivateKeyProvider(pk, "https://geth-noordung.fairdatasociety.org") },
```

doesn't!

**Comment by nosuchip** [comment]
Hi @significance I don't understand what is your problem and what kind of solution you expecting?
