### ISSUE TITLE
Cannot deploy to any network

### ISSUE THREAD

**Issue by duongvansang** [nosuchip/truffle-privatekey-provider#4]
I am trying to use privatekey provider with truffle to run migrate.

But cannot, always got error:
Error: ProviderSubprovider - specified provider does not have a sendAsync method

my sample code is here: https://github.com/duongvansang/crowdfundsample
It's very simple code with only one smart contract.

**Comment by nosuchip** [comment]
Hi @duongvansang . Please answer questions below:
- Did you tried to deploy to test network locally?
- What commands you using to compile and deploy code to network?

**Comment by duongvansang** [comment]
1. Yes, I am trying to deploy to local network (ganache 1.2.2)
2. truffle compile --all | truffle migrate

**Comment by nosuchip** [comment]
There is no such version of `ganache-cli@1.2.2` on NPM. Please provide exact  packages version you using in development (it is missing in `package.json`).

**Comment by duongvansang** [comment]
> There is no such version of `ganache-cli@1.2.2` on NPM. Please provide exact packages version you using in development (it is missing in `package.json`).

Actually, I don't use ganache-cli, I used ganache for mac, this one https://github.com/trufflesuite/ganache/releases/download/v1.2.3/Ganache-1.2.3.dmg

**Comment by duongvansang** [comment]
I am using https://github.com/trufflesuite/ganache/releases/download/v1.2.2/Ganache-1.2.2.dmg, but I think it will be the same.

**Comment by nosuchip** [comment]
What version of truffle you using? What version on solc compiler expected?

**Comment by duongvansang** [comment]
It's:
>>>truffle v
Truffle v4.1.15 (core: 4.1.15)
Solidity v0.4.25 (solc-js)

**Comment by yqsy** [comment]
i also met the problem

**Comment by dlip** [comment]
Temporary fix:

Add to package.json
```
  "resolutions": {
    "web3": "1.0.0-beta.37"
  }
```

Remove node_modules and reinstall

**Comment by dlip** [comment]
Was still hanging, so switched to truffle-hdwallet-provider which also accepts private key and it worked straight away.

**Comment by nosuchip** [comment]
@duongvansang @yqsy @dlip thank you for information and patience. Issue was fixed and new version published. Please check out `v1.1.0`.

**Comment by duongvansang** [comment]
> @duongvansang @yqsy @dlip thank you for information and patience. Issue was fixed and new version published. Please check out `v1.1.0`.

Sounds great, let me check, could I know about reason?

**Comment by nosuchip** [comment]
Of course. I used an ancient Web3.providers.HttpProvider to communicate
with node over http. This provide isn't a part of web3-providers-engine
package and must be wrapped into ProvidersSubprovider. Now it was changed
and doesn't meet subprovider interface. And was replaced by RpcProvider.

**Comment by duongvansang** [comment]
I checked on my local, all is good, thank you very much
