### ISSUE TITLE
Many redundant calls

### ISSUE THREAD

**Issue by duongvansang** [nosuchip/truffle-privatekey-provider#5]
When I try to deploy contracts using privatekey provider and I check log, there are so many calls
eth_getBlockByNumber
eth_getBlockByNumber
eth_getBlockByNumber
eth_getBlockByNumber
So performance is quite bad, could you double check?

**Comment by nosuchip** [comment]
Hi @duongvansang. It is issue not with `truffle-privatekey-provider` itself but with underlying subproviders. As I remember multiple `eth_getBlockByNumber` caused by hooks subproviders (can be found in sources ones that used in my code).

About performance: can you measure how it affects performance? Do you know any alternative solutinos that does not performs so many block by number calls?

**Comment by duongvansang** [comment]
> Hi @duongvansang. It is issue not with `truffle-privatekey-provider` itself but with underlying subproviders. As I remember multiple `eth_getBlockByNumber` caused by hooks subproviders (can be found in sources ones that used in my code).
> 
> About performance: can you measure how it affects performance? Do you know any alternative solutinos that does not performs so many block by number calls?

Yes, I am looking for it too, but don't have yet.

Basically, when we deploy a contract actually, we need to do only 3 things:
1. Get current nonce
2. Create a sign data from bytecode of contract
3. Send it to network by calling sendRawTransaction.

So I am wondering, how could we minimize the actions to network. eth_getBlockByNumber, will need read through key-value in Storage of EVM, it's quite slow when you have HDD not SSD disk.

**Comment by nosuchip** [comment]
I am afraid when using truffle infrastructure you cannot. It is supposed to be implemented multilayered. But anyway, all `READ` operations on the network is free, so when deploying you will not be charged for all these "get" operations.

But if you want to have simple solution I only can suggest any of tons articles "how to deploy contract without truffle or embark". You can compile your code using `solc` utility and then prepare simple script that deploy compiled code to the network.

**Comment by duongvansang** [comment]
Yes, I know we can use simple script to deploy contract,
but you know truffle is very popular one and can leverage dapp development process, when I explain to some intern guys, truffle could make things more simple for them.

But could you post and issue for truffle?
they should optimize their flow somehow.
