### ISSUE TITLE
Truffle 5.x: Web3ProviderEngine does not support synchronous requests.

### ISSUE THREAD

**Issue by duongvansang** [nosuchip/truffle-privatekey-provider#6]
When I deploy smart contract with Truffle 5.0.x I got issue:

Error: Error: Web3ProviderEngine does not support synchronous requests.
    at Object.run (/usr/local/share/.config/yarn/global/node_modules/truffle/build/webpack:/packages/truffle-migrate/index.js:84:1)
    at <anonymous>
Truffle v5.0.18 (core: 5.0.18)
Node v8.15.1

It is still ok with truffle v4.1.15

**Comment by nosuchip** [comment]
Hi. It is definitely not an issue of `truffle-privatekey-provider`. It is better either to use truffle 4.1.x or ask this question in truffle repository.
