### ISSUE TITLE
Error: Web3ProviderEngine does not support synchronous requests.

### ISSUE THREAD

**Issue by StillFantastic** [nosuchip/truffle-privatekey-provider#7]
When I am trying to deploy my contracts to ropsten with truffle using `truffle deploy --network ropsten --reset`:

```
Compiling your contracts...
===========================
> Everything is up to date, there is nothing to compile.

Error: Error: Web3ProviderEngine does not support synchronous requests.
    at Object.run (/home/stillfantasy/.nvm/versions/node/v11.0.0/lib/node_modules/truffle/build/webpack:/packages/truffle-migrate/index.js:92:1)
Truffle v5.0.22 (core: 5.0.22)
Node v11.0.0
```

here is my truffle.js:
```
// Allows us to use ES6 in our migrations and tests.
require('babel-register')
var PrivateKeyProvider = require("truffle-privatekey-provider")
var PrivateKey = "xxxxxxxxxxxxxxxxxxxxxxxxxxxx"

module.exports = {
  networks: {
    development: {
      host: '127.0.0.1',
      port: 7545,
      network_id: '*' // Match any network id
    },
    ropsten: {
      provider: function() {
        return new PrivateKeyProvider(PrivateKey, "https://ropsten.infura.io/v3/xxxxxxxxxxxxxxxxxxxxxxxxx")
      },
      network_id: 3,
      gas: 5000000,
      skipDryRun: true,
      gasPrice: 20000000000
    }
  }
}
```

And it works fine with truffle-hdwallet-provider, my truffer version is `5.0.22`, and truffle-privatekey-provider is `1.1.0`, please advice

**Comment by nosuchip** [comment]
1. Do you have minimal repo which can be used for reproducing this issue?
2. Please post your deployment script.

**Comment by nosuchip** [comment]
Do you have minimalistic repository to reproduce this issue?

**Comment by StillFantastic** [comment]
Hello @nosuchip ,
The error happens even with an empty truffle package. 
So to reproduce:
```
mkdir test
cd test
truffle init
npm install truffle-privatekey-provider
```
and then replace the `truffle-config.js` file with `truffle.js` above (of course need to use correct private key and infura url).
and then you can run `truffle deploy --network ropsten`

Or baybe it's node's problem?
I am currently using node(v11.0.0) with nvm.

**Comment by AndreiD** [comment]
same problem

**Comment by julesGoullee** [comment]
Hey see there https://github.com/nosuchip/truffle-privatekey-provider/pull/8. Replace in your package json 
` "truffle-privatekey-provider": "julesGoullee/truffle-privatekey-provider#fix",`

**Comment by nosuchip** [comment]
Corresponding PR merged. Please use latest version (1.2.0). Thanks @julesGoullee for fix and PR.

**Comment by nosuchip** [comment]
@StillFantastic @AndreiD @julesGoullee please check out version 1.3.0, issue was fixed.
